### PR TITLE
fix: fix dependency issues in CI

### PR DESCRIPTION
**Pull request by taeh98**
This is a work in progress, don't merge until the checks work properly.

### CODE REVIEW

**Comment by taeh98** [comment]
You can't run a GitHub Actions job on Ubuntu 23; it isn't one of [the available runners](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners). Is there some way you can run your project on Ubuntu 22 by updating the dependencies (that are up-to-date in Ubuntu 23) yourself?

**Comment by Spydr06** [comment]
I don't think that's possible since Ubuntu isn't rolling-release

**Comment by taeh98** [comment]
> I don't think that's possible since Ubuntu isn't rolling-release

Hmm ok, what do you have to do to run this project on your own computer? Do you have to install these dependencies yourself, assuming you haven't already done so for other stuff? Or are they only available as part of the distro?

**Comment by Spydr06** [comment]
Depends on the distro of course, but the `-dev` packages are normally not installed by default as they are only used for compilation. You'd have to do that yourself on a "real" Ubuntu machine too

**Comment by taeh98** [comment]
> Depends on the distro of course, but the `-dev` packages are normally not installed by default as they are only used for compilation. You'd have to do that yourself on a "real" Ubuntu machine too

OK, so presumably if we do the same as you would to make this project work on a "real" Ubuntu 22 machine, it should work for the Ubuntu 22 runners too, no? What stuff would you have to install/update to make it work on the real machine?

**Comment by Spydr06** [comment]
On a real machine it probably won't work on ubuntu 22.04 and lower since the package is wayy outdated :(

**Comment by taeh98** [comment]
> On a real machine it probably won't work on ubuntu 22.04 and lower since the package is wayy outdated :( I don't use Ubuntu for development so I never verified this.

@Spydr06 ah damn :/ So it's a library that comes packaged with Ubuntu that you can't upgrade? Which library/libraries?

**Comment by Spydr06** [comment]
seems like that, it's `libadwaita`, the ubuntu version is `1.1.7` but we need `1.2.0` or newer

**Comment by Spydr06** [comment]
I'm currently trying what it takes to download the `.deb` files manually and installing them

**Comment by Spydr06** [comment]
Compiling from source using these commands works on 22.04!!
```bash
$ apt install build-essential libcairo2-dev libgtk-4-dev valac sassc gettext git
$ git clone https://gitlab.gnome.org/GNOME/libadwaita.git -b libadwaita-1-2
$ cd libadwaita
$ ninja -C _build install
```
Can you add this procedure as a new step in the CI process?

**Comment by taeh98** [comment]
> Great news @taeh98: Compiling `libadwaita` from source works on 22.04!!
> 
>     * Install these dependencies with `apt`: `build-essential` `libcairo2-dev` `libgtk-4-dev` `meson` `valac` `sassc` `gettext` `git`
> 
>     * Run these commands:
> 
> 
> ```shell
> $ git clone https://gitlab.gnome.org/GNOME/libadwaita.git -b libadwaita-1-2 --depth=1
> $ cd libadwaita
> $ meson . _build -Dgtk_doc=false -Dtests=false -Dexamples=false
> $ ninja -C _build install
> ```
> 
> (the last command must be run with root permissions) Can you add this procedure as a new step in the CI process?

Oh, nice! I'll give it a go tomorrow and see if I can replicate it in the CI jobs :)

**Comment by Spydr06** [comment]
awesome, gl!

**Comment by taeh98** [comment]
Hey @Spydr06, does [this](https://github.com/Spydr06/logicrs/actions/runs/6383753730/job/17325028053?pr=28) look right? I might add some caching but if you think it's right then that should be it :)

**Comment by Spydr06** [comment]
Hey that's awesome, good job! (Yes caching seems like a good idea)

**Comment by taeh98** [comment]
Alright @Spydr06 I’ve finished, all the CI checks are now working :)

**Comment by Spydr06** [comment]
Awesome, tysm!

**Pull request merged**
